import Editor from "@/components/editor";
import Preview from "@/components/preview";
import { initialState } from "@/initialState";
import Head from "next/head";
import { useCallback, useState } from "react";

export default function Home(): JSX.Element {
  const [doc, setDoc] = useState<string>(initialState)

  const handleDocChange = useCallback((newDoc: string) => {
    setDoc(newDoc)
  }, [])

  return (
    <>
      <Head>
        <title>Markdown Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className='bg-gray-900 grid grid-rows-2 grid-cols-1 sm:grid-cols-2
        sm:grid-rows-1 h-screen'
      >
        <Editor onChange={handleDocChange} initialDoc={initialState} />
        <Preview doc={doc} />
      </div>
    </>
  )
}
